name: BeatFindr (email every 6 hours)

on:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours
  workflow_dispatch:        # allow manual runs

jobs:
  run-beatfindr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # explicit version

      - name: Install dependencies
        run: |
          python -V
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run BeatFindr
        env:
          PYTHONUNBUFFERED: '1'  # force immediate prints
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
          SPREADSHEET_NAME:  ${{ secrets.SPREADSHEET_NAME }}
          GMAIL_USER:        ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_TO:          ${{ secrets.EMAIL_TO }}
        run: |
          echo "DEBUG: starting workflow run"
          python - <<'PY'
import os, sys
print("DEBUG: Preflight")
print("DEBUG: SPREADSHEET_NAME =", os.environ.get("SPREADSHEET_NAME"))
print("DEBUG: GOOGLE_CREDS_JSON length =", len(os.environ.get("GOOGLE_CREDS_JSON","")))
print("DEBUG: EMAIL_TO =", os.environ.get("EMAIL_TO"))
print("DEBUG: GMAIL_USER =", os.environ.get("GMAIL_USER"))
print("DEBUG: launching main.py")
sys.stdout.flush()
PY
          python main.py
          echo "DEBUG: main.py finished"
